### ISSUE TITLE
Forever in shady mode

### ISSUE THREAD

**Issue by 11v1** [rgtk/redmine_shady#1]
Hello.

Steps to reproduce:
1. Turn on "Use shady mode" for a role by admin
2. Turn on "Shady mode" by user
3. Turn off "Use shady mode" for a role by admin
User is left in Shady mode forever and can't turn it off. The banner at the top of window persists, but "Cancel" button triggers error page.
This is the most unexpectable scenario. I think that it should work in one of two ways:
a. Turn off "Shady mode" automatically for all users without permission to use it
b. Allow users with turned on "Shady mode" to turn it off even whithout "Use shady mode" permission.

**Comment by rgtk** [comment]
Good catch. Fixed.

Checkout branch `shady-fore`: https://github.com/rgtk/redmine_shady/tree/shady-fore

Let me know if it works for you and I will merge it to master, for posterity.

**Comment by 11v1** [comment]
Won't you update version at redmine.org?
